name: Events exercices

on:
  push:
    branches:
      - "dev"
      - "!stages"

  pull_request:
    types:
      - opened
      - closed

  schedule:
    - '*/1 * * * *'
    - '30 1-23/3 * * *'
    - '* 3 * * TUE'

  - cron: '*/1 * * * *'
  - cron: '30 */1 * * *'
  - cron: '0 3 * * 2'

jobs:
  print-event:
    runs-on: ubuntu-latest

    steps:
      - name: Print the event that triggered this workflow
        run: |
          echo push on dev

      - name: Print the current time
        run: |
          echo $(date)