#Write a workflow that installs dependancies and runs the test. Specify a default folder for all the steps inside the job.
#Create a matrix strategy for a node js app that will install dependancies for node 12, 14, 16
#Create a second matrix strategy to test the node app on ubuntu and windows


name: Runner

on:
  push:
    branches:
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: node-app
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test
      - name: Install dependancies
        run: npm install

      - name: Run tests
        run: npm test